"use client";

import { motion } from "framer-motion";
import {
  Brain,
  BarChart3,
  Wifi,
  Sparkles,
  Plus,
  Clock,
  Target,
  Zap,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "Spaced repetition",
    description:
      "Our algorithm knows when you're about to forget. Review words at the perfect moment to lock them in your long-term memory.",
    color: "bg-purple-100 text-purple-600",
  },
  {
    icon: BarChart3,
    title: "Track your progress",
    description:
      "See your daily, weekly, and monthly learning stats. Watch your vocabulary grow with beautiful visualizations.",
    color: "bg-blue-100 text-blue-600",
  },
  {
    icon: Wifi,
    title: "Works offline",
    description:
      "No internet? No problem. Your flashcards sync when you're back online. Learn anywhere, anytime.",
    color: "bg-green-100 text-green-600",
  },
  {
    icon: Plus,
    title: "Add your own words",
    description:
      "Heard a new word? Add it instantly. Build a personalized vocabulary that matches your real-life conversations.",
    color: "bg-orange-100 text-orange-600",
  },
  {
    icon: Sparkles,
    title: "AI-powered examples",
    description:
      "Get contextual example sentences generated by AI. See how words are actually used in everyday Lebanese Arabic.",
    color: "bg-pink-100 text-pink-600",
  },
  {
    icon: Clock,
    title: "Learn at your pace",
    description:
      "No pressure, no deadlines. The app adapts to your schedule and remembers where you left off.",
    color: "bg-cyan-100 text-cyan-600",
  },
  {
    icon: Target,
    title: "Focus mode",
    description:
      "Boost specific words you want to master faster. Perfect for preparing conversations or trips.",
    color: "bg-amber-100 text-amber-600",
  },
  {
    icon: Zap,
    title: "Quick review sessions",
    description:
      "Got 5 minutes? That's enough. Short, focused sessions that fit into your busy life.",
    color: "bg-rose-100 text-rose-600",
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
    },
  },
};

export function FeaturesSection() {
  return (
    <section id="features" className="py-24 bg-white">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <motion.span
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="inline-block px-4 py-1.5 rounded-full bg-gray-100 text-gray-600 text-sm font-medium mb-4"
          >
            Features
          </motion.span>
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="font-pphatton text-4xl sm:text-5xl font-bold text-gray-900 mb-4"
          >
            Everything you need to learn
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
            className="text-lg text-gray-600 max-w-2xl mx-auto"
          >
            Simple, powerful tools designed to make learning Lebanese Arabic
            feel natural and enjoyable.
          </motion.p>
        </div>

        {/* Features Grid */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              variants={itemVariants}
              className="group p-6 rounded-2xl bg-gray-50 hover:bg-white hover:shadow-xl hover:shadow-gray-100/50 border border-transparent hover:border-gray-100 transition-all duration-300"
            >
              <div
                className={`w-12 h-12 rounded-xl ${feature.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}
              >
                <feature.icon className="w-6 h-6" />
              </div>
              <h3 className="font-semibold text-gray-900 text-lg mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-600 text-sm leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
